In [11]:
import numpy as np

In [54]:
path = '/home/elfat/python_env/Geometric Deep Learning/FMRI data/'

labels = np.load(path + 'labels.npy')
corrs = np.load(path + 'corrs.npy')

# Описание
Объекты -- матрицы корреляций активностей 12 регионов головного мозга, входящих в определённую подсеть.
X[i] определяет соответствующий набор корреляций, всего систем 4 (visual cortex, smn, attention network, dmn).

И есть три разметки.
Первая определяет номер пациента (3 класса).
Вторая определяет, проводился замер в первой или второй половине эксперимента (два класса).
Третья указывает на resting-state (два сильно несбалансированных класса).

In [9]:
visual_cortex, smn, attention_network, dmn = corrs
patient_id, experiment_part_id, resting_state = labels

In [10]:
np.unique(patient_id, return_counts=True), np.unique(experiment_part_id, return_counts=True), np.unique(resting_state, return_counts=True)

((array([1, 2, 5]), array([478, 464, 478])),
 (array([0, 1]), array([720, 700])),
 (array([0, 1]), array([1332,   88])))

# Data preprocessing

In [34]:
from sklearn.model_selection import train_test_split

X, y = visual_cortex, resting_state

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, stratify=resting_state)

In [35]:
np.unique(y_test, return_counts=True)

(array([0, 1]), array([440,  29]))

In [32]:
# !pip install --upgrade imbalanced-learn

In [49]:
from imblearn.over_sampling import RandomOverSampler


def resample_data(X, y):
    X_idx = np.expand_dims(np.arange(0, X.shape[0]), axis=1)
    ros = RandomOverSampler(random_state=0)
    X_resampled, y_resampled = ros.fit_resample(X_idx, y)
    X_resampled = X[X_resampled.squeeze()]
    return X_resampled, y_resampled

In [53]:
X_resampled, y_resampled = resample_data(X_train, y_train)

print(f"X_train: {X_train.shape} X_resampled: {X_resampled.shape}")
print(f"y_train: {np.unique(y_train, return_counts=True)} y_resampled: {np.unique(y_resampled, return_counts=True)}")

X_train: (951, 12, 12) X_resampled: (1784, 12, 12)
y_train: (array([0, 1]), array([892,  59])) y_resampled: (array([0, 1]), array([892, 892]))
